"""Initial migration

Revision ID: 765b85e060d1
Revises: 
Create Date: 2025-06-10 17:34:45.233445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765b85e060d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_to_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.Enum('USER', 'BOT', name='messageauthor'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_to_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_response_to_id'), 'messages', ['response_to_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=False),
    sa.Column('bucket_name', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('number_of_chunks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_created_at'), 'source_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_documents_object_name'), 'source_documents', ['object_name'], unique=True)
    op.create_index(op.f('ix_source_documents_status'), 'source_documents', ['status'], unique=False)
    op.create_table('text_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('sequence_in_document', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_chunks_created_at'), 'text_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_text_chunks_source_document_id'), 'text_chunks', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_chunks_source_document_id'), table_name='text_chunks')
    op.drop_index(op.f('ix_text_chunks_created_at'), table_name='text_chunks')
    op.drop_table('text_chunks')
    op.drop_index(op.f('ix_source_documents_status'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_object_name'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_created_at'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_messages_response_to_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
